FROM python
WORKDIR /app
COPY hello.py .
# COPY start-app.sh .
# since we defined ENV we do not need anymore start-app.sh
RUN pip install flask
ENV FLASK_APP "hello"
ENV FLASK_ENV "development"
ENV FLASK_RUN_HOST "0.0.0.0"
CMD ["flask","run"]
