docker build -t flask-hello https://github.com/pythonincontainers/flask-hello.git

the whole content is downloaded ! as context

there is a Dockerfile inside like below:

<!-- FROM python
WORKDIR /myproject
COPY . .
RUN pip install -r requirements.txt
EXPOSE 5000
ENV FLASK_DEBUG=True
CMD python flask-hello.py -->
